require('derek.globals')
require('derek.plugins')
require('derek.completion')
require('derek.treesitter')
require('derek.lsp')
require('derek.formatting')
require('derek.telescope')
require('derek.leaders')
