#!/usr/bin/env bash
#
# Run all dotfiles installers.

if test ! "$(uname)" = "Darwin"
then
  exit 0
fi

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

